// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22/07/2026 22:09:25
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ADMIN/Desktop/Jordane/MonCv/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/plugins/**/*.{js,ts,mjs}","C:/Users/ADMIN/Desktop/Jordane/MonCv/composables/**/*.{js,ts,mjs}","C:/Users/ADMIN/Desktop/Jordane/MonCv/utils/**/*.{js,ts,mjs}","C:/Users/ADMIN/Desktop/Jordane/MonCv/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ADMIN/Desktop/Jordane/MonCv/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;