// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01/03/2026 21:45:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/plugins/**/*.{js,ts,mjs}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/composables/**/*.{js,ts,mjs}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/utils/**/*.{js,ts,mjs}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/MonCv/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;