// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01/03/2026 21:33:15
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/plugins/**/*.{js,ts,mjs}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/composables/**/*.{js,ts,mjs}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/utils/**/*.{js,ts,mjs}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/PROMESSE ING/Downloads/portfolio/package/ryan/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;